export const quotes = function () {
	const allquotes = [
		"Ese cerebro mío es algo más que un simple mortal; como el tiempo lo demostrará",
		"Si no puedes darme poesía, ¿no puedes darme ciencia poética?",
		"La religión para mí es ciencia y la ciencia es religión",
		"Cuanto más estudio, más insaciable siento mi genialidad por serlo",
		"Tu mejor y más sabio refugio de todos los problemas está en tu ciencia",
		"La ciencia de las operaciones, derivada de las matemáticas más especialmente, es una ciencia en sí misma y tiene su propia verdad y valor abstractos",
		"La imaginación es la Facultad de Descubrimiento, por excelencia. Es aquello que penetra en los mundos invisibles que nos rodean, los mundos de la Ciencia",
		"La ciencia matemática muestra lo que es. Es el lenguaje de las relaciones invisibles entre las cosas. Pero para usar y aplicar ese lenguaje, debemos ser capaces de apreciar plenamente, sentir, captar lo invisible, el inconsciente",
		"Tan pronto como logré volar a la perfección, obtuve un esquema sobre una máquina de vapor",
		"La vida no es fácil para ninguno de nosotros. ¿Pero qué hay de eso? Debemos tener constancia y sobre todo confianza en nosotros mismos. Debemos creer que estamos dotados para algo y que eso se debe lograr",
		"Nada en la vida es de temer, solo es de comprender. Ahora es el momento de comprender más, para que podamos temer menos",
		"Uno nunca se da cuenta de lo que se ha hecho; uno solo puede ver lo que queda por hacer",
		"Un científico en su laboratorio no es un mero técnico: también es un niño que se enfrenta a fenómenos naturales que le impresionan como si fueran cuentos de hadas.",
		"Sé menos curioso acerca de las personas y más curioso acerca de las ideas.",
		"Me enseñaron que el camino del progreso no era rápido ni fácil",
		"Hay científicos sádicos que se apresuran a cazar errores en lugar de establecer la verdad",
		"Es mi ferviente deseo que algunos de ustedes continúen con este trabajo científico y mantengan como ambición la determinación de hacer una contribución permanente a la ciencia",
		"Soy de los que piensan como Nobel, que la humanidad sacará más bien que mal de los nuevos descubrimientos.",
		"Frecuentemente me han cuestionado, sobre todo mujeres, de cómo podría conciliar la vida familiar con una carrera científica. Bueno, no ha sido fácil.",
		"Durante toda mi vida, las nuevas vistas de la Naturaleza me hicieron regocijarme como un niño",
		"No se puede aspirar a construir un mundo mejor sin mejorar a los individuos. Para ello, cada uno de nosotros debe trabajar por su propio mejoramiento, y al mismo tiempo compartir una responsabilidad general para con toda la humanidad, siendo nuestro deber particular ayudar a aquellos a quienes debemos creo que podemos ser más útiles.",
		"Soy de los que piensan que la ciencia tiene una gran belleza.",
		"Un barco en el puerto es seguro, pero no es para eso que se construyen los barcos",
		"La única frase que nunca me ha gustado es: 'Por qué, siempre lo hemos hecho de esa manera'. Siempre les digo a los jóvenes: 'Adelante, hazlo. Siempre puedes disculparte más tarde'",
		"Una medida precisa vale más que mil opiniones de expertos.",
		"El liderazgo es una calle de doble sentido, lealtad hacia arriba y lealtad hacia abajo. Respeto por los superiores; cuidado por la tripulación",
		"Siempre me ha interesado más el futuro que el pasado.",
		"El vaso no está ni medio vacío ni medio lleno. Es simplemente más grande de lo que debe ser",
		"Si haces algo una vez, la gente lo llamará accidente. Si lo haces dos veces, lo llamarán coincidencia. ¡Pero hazlo una tercera vez y acabas de probar una ley natural!",
		"En los días de los pioneros, usaban bueyes para tirar pesado, y cuando un buey no podía mover un tronco, no intentaban hacer crecer un buey más grande. No deberíamos intentar tener computadoras más grandes, sino más sistemas de computadoras. ",
		"Gestionar cosas. Liderar personas.",
		"Tendemos a olvidar que ninguna computadora hará una nueva pregunta",
		"Si no está atornillado, tráelo a casa",
		"No tomaré lo que necesitas darme. Tomaré lo que quieras darme",
		"Para mí, la programación es más que un arte práctico importante. También es una empresa gigantesca en los cimientos del conocimiento",
		"Las chicas son capaces de hacer todo lo que los hombres son capaces de hacer. A veces tienen más imaginación que los hombres",
		"No tengo un sentimiento de inferioridad. Nunca lo he tenido. Soy tan bueno como cualquiera, pero no mejor",
		"Te gusta lo que haces, y luego harás lo mejor que puedas",
		"Necesitábamos ser asertivas como mujeres en esos días, asertivas y agresivas, y el grado en que teníamos que ser así dependía de dónde estabas. Tenía que serlo",
		"Me gusta aprender. Eso es un arte y una ciencia",
		"En matemáticas, o tienes razón o estás equivocado",
		"Conté todo. Conté los pasos hasta la calle, los pasos hasta la iglesia, la cantidad de platos y cubiertos que lavé... todo lo que se podía contar, lo hice",
		// "That brain of mine is something more than merely mortal; as time will show.",
		// "If you can’t give me poetry, can’t you give me poetical science?",
		// "Religion to me is science and science is religion.",
		// "The more I study, the more insatiable do I feel my genius for it to be.",
		// "Your best and wisest refuge from all troubles is in your science.",
		// "The science of operations, as derived from mathematics more especially, is a science of itself, and has its own abstract truth and value.",
		// "Imagination is the Discovering Faculty, pre-eminently. It is that which penetrates into the unseen worlds around us, the worlds of Science.",
		// "Mathematical science shows what is. It is the language of unseen relations between things. But to use and apply that language, we must be able to fully to appreciate, to feel, to seize the unseen, the unconscious.",
		// "As soon as I have got flying to perfection, I have got a scheme about a steam engine.",
		// "Life is not easy for any of us. But what of that? We must have perseverance and above all confidence in ourselves. We must believe that we are gifted for something and that this thing must be attained.",
		// "Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less.",
		// "One never notices what has been done; one can only see what remains to be done.",
		// "A scientist in his laboratory is not a mere technician: he is also a child confronting natural phenomena that impress him as though they were fairy tales.",
		// "Be less curious about people and more curious about ideas.",
		// "I was taught that the way of progress was neither swift nor easy.",
		// "There are sadistic scientists who hurry to hunt down errors instead of establishing the truth.",
		// "It is my earnest desire that some of you should carry on this scientific work and keep for your ambition the determination to make a permanent contribution to science.",
		// "I am one of those who think like Nobel, that humanity will draw more good than evil from new discoveries.",
		// "I have frequently been questioned, especially by women, of how I could reconcile family life with a scientific career. Well, it has not been easy.",
		// "All my life through, the new sights of Nature made me rejoice like a child.",
		// "You cannot hope to build a better world without improving the individuals. To that end each of us must work for his own improvement, and at the same time share a general responsibility for all humanity, our particular duty being to aid those to whom we think we can be most useful.",
		// "I am among those who think that science has great beauty.",
		// "A ship in port is safe, but that’s not what ships are built for.",
		// "The only phrase I’ve ever disliked is, ‘Why, we’ve always done it that way.’ I always tell young people, ‘Go ahead and do it. You can always apologize later.'",
		// "One accurate measurement is worth a thousand expert opinions.",
		// "Leadership is a two-way street, loyalty up and loyalty down. Respect for one’s superiors; care for one’s crew.",
		// "I’ve always been more interested in the future than in the past.",
		// "The glass is neither half empty nor half full. It’s simply larger than it needs to be.",
		// "If you do something once, people will call it an accident. If you do it twice, they call it a coincidence. But do it a third time and you’ve just proven a natural law!",
		// "In pioneer days they used oxen for heavy pulling, and when one ox couldn’t budge a log, they didn’t try to grow a larger ox. We shouldn’t be trying for bigger computers, but for more systems of computers.",
		// "Manage things. Lead people.",
		// "We’ve tended to forget that no computer will ever ask a new question.",
		// "If it isn’t bolted down, bring it home.",
		// "I will not take what you need to give me. I will take what you want to give me.",
		// "To me programming is more than an important practical art. It is also a gigantic undertaking in the foundations of knowledge.",
		// "Girls are capable of doing everything men are capable of doing. Sometimes they have more imagination than men.",
		// "I don’t have a feeling of inferiority. Never had. I’m as good as anybody, but no better.",
		// "Like what you do, and then you will do your best.",
		// "We will always have STEM with us. Some things will drop out of the public eye and will go away, but there will always be science, engineering, and technology. And there will always, always be mathematics.",
		// "We needed to be assertive as women in those days – assertive and aggressive – and the degree to which we had to be that way depended on where you were. I had to be.",
		// "I like to learn. That’s an art and a science.",
		// "In math, you’re either right or you’re wrong.",
		// "I counted everything. I counted the steps to the road, the steps up to church, the number of dishes and silverware I washed … anything that could be counted, I did.",
		// "The women did what they were told to do. They didn’t ask questions or take the task any further. I asked questions; I wanted to know why. They got used to me asking questions and being the only woman there.",
		// "You are no better than anyone else, and no one is better than you.",
		// "Take all the courses in your curriculum. Do the research. Ask questions. Find someone doing what you are interested in! Be curious!",
		// "I see a picture right now that’s not parallel, so I’m going to go straighten it. Things must be in order.",
		// "Everything was so new – the whole idea of going into space was new and daring. There were no textbooks, so we had to write them.",
		// "Let me do it. You tell me when you want it and where you want it to land, and I’ll do it backwards and tell you when to take off.",
	];
	return allquotes;
};

export function randomnumber(min, max) {
	const numerorandom = Math.floor(Math.random() * (max - min + 1) + min);
	return numerorandom;
}
