import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import css from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Clock App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={css.main}>
				<section id="superior">
					<div className={css.quote}>
						<p>camaron que se duerme se lo lleva la corriente</p>
						<span>Chapulin colorado</span>
					</div>

					<div className={css.hora}>
						<div className={css.mensaje}>
							<img alt="sol/luna" />
							<p>good morning</p>
						</div>
					</div>
				</section>
			</main>
		</>
	);
}
