import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

import { randomnumber, quotes } from "../helpers/helpers";

import TheTime from "../components/TheTime";

import css from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

function TheQuotes(props) {
	const { author, thequote } = props;
	return (
		<div className={css.quote}>
			<p>{`"${thequote}"`}</p>
			<strong>{author}</strong>
		</div>
	);
}

export async function getServerSideProps() {
	let quote = quotes();
	quote = quote[randomnumber(0, quote.length - 1)];

	const forestDay = `/assets/images/day/forest${randomnumber(1, 6)}-min.jpg`;

	return {
		props: { forestDay, quote },
	};
}

export default function Home({ forestDay, quote }) {
	return (
		<>
			<Head>
				<title>Clock App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={css.main} style={{ background: `url("${forestDay}")`, backgroundSize: "cover" }}>
				<section className={css.superior}>
					<TheQuotes thequote={quote} author="Ada Lovelace" />

					<TheTime />
				</section>
			</main>
		</>
	);
}
